name: khu_farm
description: "KHU:FARM"
publish_to: 'none'

version: 1.0.2+10

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  change_app_package_name: ^1.5.0
  
  http: ^1.1.0
  intl: ^0.20.2

  flutter_secure_storage: ^9.0.0

  flutter_quill: ^11.0.0
  flutter_quill_extensions: ^11.0.0
  flutter_localization: ^0.3.0
  cupertino_icons: ^1.0.8

  flutter_markdown: ^0.7.1

  image_picker: ^1.0.0

  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.6
  table_calendar: ^3.0.8

  pedometer: ^4.1.1
  shared_preferences: ^2.5.0
  permission_handler: ^12.0.0
  daum_postcode_search: ^0.0.2

  flutter_inappwebview: ^6.0.0

  portone_flutter: ^0.12.0

  geolocator: ^14.0.0

  firebase_core: ^4.0.0
  firebase_messaging: ^16.0.0
  flutter_local_notifications: ^19.4.0

  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/app_icon.png"

flutter:
  uses-material-design: true
  fonts:
    - family: LogoFont
      fonts:
        - asset: assets/fonts/RixInooAriDuri Regular.ttf
    - family: default
      fonts:
        - asset: assets/fonts/PRETENDARD-MEDIUM.OTF

  assets:
    - assets/splash/splash.png
    - assets/splash/splash_background.png
    - assets/splash/splash_square.png
    - assets/notch/morning.png
    - assets/notch/morning_right_up_cloud.png
    - assets/notch/morning_left_down_cloud.png
    - assets/mascot/login_mascot.png
    - assets/mascot/sad_mascot.png
    - assets/icons/goback.png
    - assets/icons/consumer.png
    - assets/icons/retailer.png
    - assets/icons/farmer.png
    - assets/icons/apple.png
    - assets/icons/mandarin.png
    - assets/icons/tangor.png
    - assets/icons/korean_melon.png
    - assets/mascot/main_mascot.png
    - assets/bottom_navigator/unselect/daily.png
    - assets/bottom_navigator/unselect/stock.png
    - assets/bottom_navigator/unselect/harvest.png
    - assets/bottom_navigator/unselect/laicos.png
    - assets/bottom_navigator/unselect/mypage.png
    - assets/bottom_navigator/select/daily.png
    - assets/bottom_navigator/select/stock.png
    - assets/bottom_navigator/select/harvest.png
    - assets/bottom_navigator/select/laicos.png
    - assets/bottom_navigator/select/mypage.png
    - assets/weather/cloudy.png
    - assets/weather/rain.png
    - assets/weather/snow.png
    - assets/weather/sunny.png
    - assets/top_icons/notice.png
    - assets/top_icons/notice_selected_morning.png
    - assets/top_icons/dibs.png
    - assets/top_icons/dibs_selected_morning.png
    - assets/top_icons/cart.png
    - assets/top_icons/cart_selected_morning.png
    - assets/harvest/seed.png
    - assets/harvest/stem.png
    - assets/harvest/fruit.png
    - assets/chat/chatbot_icon.png
    - assets/farm/temp_farm.jpg
    - assets/app_icon.png

flutter_native_splash:
  color: "#FFFFFF"

  # 2. 중앙에 표시될 아이콘 이미지를 지정합니다.
  image: assets/splash/splash_square.png
  
  # 3. 모든 플랫폼에 적용합니다.
  android: true
  ios: true

  android_12:
    image: "assets/splash/splash_square.png"
    color: "#FFFFFF"